/* Exercise the isolated fixture; no live model or engine installations. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const base=process.env.INFLECT_TEST_URL||'http://127.0.0.1:7861';
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1600,height:1000}});
 const page=await context.newPage();const errors=[];
 page.on('pageerror',error=>errors.push(String(error)));
 await page.route('**/api/settings/comfyui/discover',route=>route.fulfill({json:{containers:[{name:'test-comfy',state:'running'}],url:'http://127.0.0.1:8188',detected:true}}));
 await page.goto(base);await page.getByRole('button',{name:'Settings',exact:true}).click();
 const nav=page.getByRole('navigation',{name:'Settings sections'});
 const settings=page.getByRole('main',{name:'Inflect settings'});
 await page.getByRole('switch',{name:'Allow network access'}).waitFor();
 // Reset only this fixture's settings between runs.
 const initial=await (await page.request.get(base+'/api/settings')).json();
 if(!initial.values.network_enabled||!initial.values.comfyui_enabled){await page.request.put(base+'/api/settings',{headers:{'X-Inflect-Local':'1'},data:{revision:initial.revision,values:{...initial.values,network_enabled:true,comfyui_enabled:true}}});await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).click();}
 assert.equal(await page.getByRole('switch',{name:'Allow network access'}).getAttribute('aria-checked'),'true');
 await page.waitForTimeout(250);await page.screenshot({path:'/tmp/inflect-settings-network.png',fullPage:true});
 await page.getByRole('switch',{name:'Allow network access'}).click();
 await settings.getByRole('button',{name:'Save changes',exact:true}).click();
 await page.getByText('Settings saved. ComfyUI changes apply to the next model load.').waitFor();
 await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).click();
 assert.equal(await page.getByRole('switch',{name:'Allow network access'}).getAttribute('aria-checked'),'false');
 await nav.getByRole('button',{name:/ComfyUI/}).click();
 await page.getByRole('switch',{name:'ComfyUI integration'}).waitFor();
 assert.equal(await page.getByRole('switch',{name:'ComfyUI integration'}).getAttribute('aria-checked'),'true');
 await page.getByRole('switch',{name:'ComfyUI integration'}).click();
 await settings.getByRole('button',{name:'Save changes',exact:true}).click();
 await page.getByText('Settings saved. ComfyUI changes apply to the next model load.').waitFor();
 assert.equal(await page.getByLabel('ComfyUI address',{exact:true}).isDisabled(),true);
 await page.getByRole('switch',{name:'ComfyUI integration'}).click();
 await page.getByLabel('ComfyUI address',{exact:true}).fill('http://192.168.1.100:8188');
 await settings.getByRole('button',{name:'Save changes',exact:true}).click();
 await page.getByRole('alert').waitFor();
 assert.match(await page.getByRole('alert').innerText(),/local ComfyUI/);
 await settings.getByRole('button',{name:'Discard',exact:true}).click();
 await nav.getByRole('button',{name:/Engines/}).click();
 await page.getByRole('heading',{name:'llama.cpp',exact:true}).waitFor();
 await page.screenshot({path:'/tmp/inflect-settings-engines.png',fullPage:true});
 await nav.getByRole('button',{name:/Model setup/}).click();
 await page.getByLabel('Context window').waitFor();
 await page.screenshot({path:'/tmp/inflect-settings-model.png',fullPage:true});
 await page.getByRole('button',{name:'Back to chat'}).click();
 assert.equal(await page.locator('.workbench .settings-panel').count(),0);
 await page.getByRole('button',{name:'Model settings',exact:true}).click();
 await page.getByLabel('Context window').waitFor();
 await nav.getByRole('button',{name:/Model library/}).click();
 await page.getByLabel('Model folder',{exact:true}).fill('/does-not-exist-for-settings-test');
 await settings.getByRole('button',{name:'Save changes',exact:true}).click();
 await page.getByRole('alert').waitFor();
 assert.match(await page.getByRole('alert').innerText(),/unavailable/);
 await settings.getByRole('button',{name:'Discard',exact:true}).click();
 await nav.getByRole('button',{name:/Network/}).click();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/tmp/inflect-settings-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'mobile should not overflow');
 assert.deepEqual(errors,[]);
 console.log('Settings navigation, persistence, validation, ComfyUI opt-out, model controls, engine versions, and mobile layout passed.');
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
