import React, {useEffect, useLayoutEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, Copy, Pencil, RotateCcw, ArrowDown, ArrowUpRight, Check, ChevronDown, CircleHelp, Cpu, Database, Eye, Gauge, HardDrive, ImagePlus, Layers, LoaderCircle, MessageSquare, Play, Plus, Power, RefreshCw, Save, Search, Settings2, Sparkles, Square, Terminal, Trash2, X, Zap} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import './style.css';
import {Modal, Performance, medianPrompt, formatNumber} from './ui';
import './refinements.css';

type Model = {id:string; name:string; title:string; format:string; quant:string; architecture:string; context:number; vision:boolean; mtp:boolean; draft_limit:number; experts:number; bytes:number; issues:string[]; recommended:boolean; engines:string[]; reasoning?:{toggle:boolean;levels:string[];default_effort:string|null;options:string[]}; receipt?:{status:string;commit:string;verified_utc:string}; path:string};
type Settings = {model_id:string;engine:string;context:number;kv:string;vision:boolean;prediction:string;draft_tokens:number;max_output:number;cpu_percent:number;cpu_threads:number;chunk_size:number;temperature:number;reasoning_effort:string};
type Message = {role:'user'|'assistant';content:string;reasoning?:string;image?:string;metrics?:any;error?:boolean;cancelled?:boolean};
type Profile = {id:string;name:string;settings:Settings;updated_at?:number;deleted_at?:number};
const number = formatNumber;
const gib = (n:number|undefined|null) => n == null ? '—' : number(n / 2**30, n < 2**30 ? 2 : 1);
const short = (n:number) => n>=1024 ? `${n/1024}K` : `${n}`;
const effortLabel = (value:string) => ({default:'Model default',off:'Off',on:'On',minimal:'Minimal',low:'Low',medium:'Medium',high:'High',xhigh:'Extra high',max:'Max'}[value]||value);
const normalizeSettings = (value:Settings & {thinking?:boolean}):Settings => {
  const {thinking,...settings}=value;
  return {...settings,reasoning_effort:settings.reasoning_effort??(thinking===false?'off':'default')};
};
const defaults = (model:Model):Settings => {
  const qwen=model.name.startsWith('Qwen3.8-Flash-Next-EXL3');
  const deep=model.name.startsWith('DeepSeek')&&model.format==='EXL3';
  return {model_id:model.id,engine:'auto',context:Math.min(262144,model.context),kv:'Q8',vision:model.vision,
    prediction:qwen||deep?'mtp':'off',draft_tokens:deep?3:2,max_output:Math.min(4096,Math.floor(model.context/4)),
    cpu_percent:qwen?60:80,cpu_threads:8,chunk_size:1024,temperature:0.7,reasoning_effort:'default'};
};

async function api(path:string, body?:unknown, method?:string) {
  const response = await fetch(path,{method:method||(body === undefined?'GET':'POST'),headers:body===undefined&&!method?{}:{'Content-Type':'application/json','X-Lumen-Local':'1'},body:body===undefined?undefined:JSON.stringify(body)});
  if(!response.ok){let data;try{data=await response.json()}catch{data={detail:response.statusText}}throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail))}
  return response.json();
}

async function writeClipboard(text:string) {
  try {
    if(navigator.clipboard){await navigator.clipboard.writeText(text);return}
  } catch {}
  const area=document.createElement('textarea');
  area.value=text;area.readOnly=true;area.style.position='fixed';area.style.opacity='0';area.style.pointerEvents='none';
  document.body.appendChild(area);area.select();const copied=document.execCommand('copy');area.remove();
  if(!copied)throw new Error('Clipboard unavailable');
}

function Markdown({text}:{text:string}) {
  return <ReactMarkdown components={{img:({src,alt})=><a href={typeof src==='string'?src:undefined} target="_blank" rel="noreferrer">{alt||'Open image link'}</a>,a:({children,href})=><a href={href} target="_blank" rel="noreferrer">{children}</a>}}>{text}</ReactMarkdown>;
}

function Toggle({checked,onChange,disabled=false,label}:{checked:boolean;onChange:(v:boolean)=>void;disabled?:boolean;label:string}) {
  return <button type="button" role="switch" aria-checked={checked} aria-label={label} disabled={disabled} className={`toggle ${checked?'on':''}`} onClick={()=>onChange(!checked)}><span/></button>;
}

function Metric({icon:Icon,label,value,unit,detail,percent,history}:{icon:any;label:string;value:string;unit?:string;detail:string;percent?:number|null;history?:number[]}) {
  return <div className="metric"><div className="metric-label"><Icon size={15}/>{label}{history&&<svg className="sparkline" viewBox="0 0 78 20" aria-hidden="true"><polyline points={history.map((v,i)=>`${i*78/Math.max(history.length-1,1)},${19-Math.min(v,100)*.18}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>}</div><div className="metric-value">{value}<span>{unit}</span></div><div className="metric-detail">{detail}</div>{percent!=null&&<div className="meter"><i style={{width:`${Math.min(percent,100)}%`}}/></div>}</div>;
}

function App(){
  const [models,setModels]=useState<Model[]>([]), [inventoryErrors,setInventoryErrors]=useState<string[]>([]), [modelRoot,setModelRoot]=useState('');
  const [selected,setSelected]=useState<Model|null>(null), [settings,setSettings]=useState<Settings|null>(null), [status,setStatus]=useState<any>(null);
  const [view,setView]=useState<'workbench'|'benchmarks'|'profiles'>('workbench'), [tab,setTab]=useState<'chat'|'details'>('chat');
  const [query,setQuery]=useState(''), [showAll,setShowAll]=useState(false), [messages,setMessages]=useState<Message[]>([]), [input,setInput]=useState('');
  const [attachment,setAttachment]=useState<string>(), [streaming,setStreaming]=useState(false), [error,setError]=useState(''), [toast,setToast]=useState('');
  const [logs,setLogs]=useState<string[]|null>(null), [profiles,setProfiles]=useState<Profile[]>([]), [benchmarks,setBenchmarks]=useState<any[]>([]);
  const [profileName,setProfileName]=useState(''), [saveOpen,setSaveOpen]=useState(false), [acting,setActing]=useState(false), [offline,setOffline]=useState(false), [closed,setClosed]=useState(false);
  const [cpuHistory,setCpuHistory]=useState<number[]>([]), [powerHistory,setPowerHistory]=useState<number[]>([]), [usedContext,setUsedContext]=useState<number|null>(null);
  const [editingId,setEditingId]=useState<string|null>(null), [saveMode,setSaveMode]=useState<'create'|'update'|'rename'>('create'), [saveTarget,setSaveTarget]=useState<Profile|null>(null), [profileError,setProfileError]=useState('');
  const [deletedProfiles,setDeletedProfiles]=useState<Profile[]>([]), [showDeleted,setShowDeleted]=useState(false), [undoProfile,setUndoProfile]=useState<Profile|null>(null);
  const [cpuPowerHistory,setCpuPowerHistory]=useState<number[]>([]), [showLatest,setShowLatest]=useState(false), [dragging,setDragging]=useState(false), [copyIndex,setCopyIndex]=useState<number|null>(null), [copiedProfileId,setCopiedProfileId]=useState<string|null>(null);
  const followTail=useRef(true), chatRef=useRef<HTMLDivElement>(null), chatContentRef=useRef<HTMLDivElement>(null), textRef=useRef<HTMLTextAreaElement>(null);
  const chats=useRef(new Map<string,{messages:Message[];input:string;attachment?:string;usedContext:number|null}>());
  const draftSettings=useRef<Settings|null>(null), selectedId=useRef<string|null>(null), lastEngineSettings=useRef<Settings|null>(null);
  const stopped=useRef(false);
  const fileRef=useRef<HTMLInputElement>(null), bottomRef=useRef<HTMLDivElement>(null), controller=useRef<AbortController|null>(null);
  draftSettings.current=settings;selectedId.current=selected?.id||null;
  const editingProfile=profiles.find(p=>p.id===editingId);
  const profileDirty=!!editingProfile&&JSON.stringify(editingProfile.settings)!==JSON.stringify(settings);
  const session=status?.session, hardware=status?.hardware, gpu=hardware?.gpu, ram=hardware?.ram;
  const ready=session?.state==='ready', loading=session?.state==='loading'||session?.state==='stopping', active=ready&&session?.model?.id===selected?.id;
  const installed=status?.engines?.find((e:any)=>e.id===(settings?.engine==='auto'?selected?.engines[0]:settings?.engine))?.installed;
  const dirty=active&&settings&&session?.settings&&Object.entries(settings).some(([k,v])=>!['max_output','temperature','engine','reasoning_effort'].includes(k)&&session.settings[k]!==v);
  const busy=streaming||session?.busy||session?.benchmark?.state==='running';

  const choose=(model:Model,preset?:Settings,profile?:Profile)=>{
    if(streaming)return;
    if(selected&&selected.id!==model.id)chats.current.set(selected.id,{messages,input,attachment,usedContext});
    if(selected?.id!==model.id){const saved=chats.current.get(model.id);setMessages(saved?.messages||[]);setInput(saved?.input||'');setAttachment(saved?.attachment);setUsedContext(saved?.usedContext??null);followTail.current=true;setShowLatest(false)}
    setSelected(model);setSettings(normalizeSettings(preset||(session?.model?.id===model.id?session.settings:defaults(model))));setEditingId(profile?.id||null);setError('');setView('workbench');setTab('chat');
  };
  const update=(key:keyof Settings,value:any)=>setSettings(s=>s?({...s,[key]:value,...(key==='context'&&s.max_output>=value?{max_output:Math.min(4096,value/4)}:{})}):s);
  const refresh=async(initial=false)=>{try{const data=await api(initial?'/api/library':'/api/library/refresh',initial?undefined:{});setModels(data.models);setInventoryErrors(data.errors);setModelRoot(data.root);if(initial&&data.models.length){const current=await api('/api/status');setStatus(current);const loaded=data.models.find((m:Model)=>m.id===current.session.model?.id);choose(loaded||data.models[0],loaded?current.session.settings:undefined);}if(!initial)setToast('Model library refreshed')}catch(e){setError(String(e))}};
  useEffect(()=>{refresh(true);api('/api/profiles').then(setProfiles).catch(()=>{});api('/api/benchmarks').then(setBenchmarks).catch(()=>{});
    let running=false;const poll=async()=>{if(running||stopped.current)return;running=true;try{const data=await api('/api/status');setStatus(data);if(data.session.settings){if(selectedId.current===data.session.model?.id&&lastEngineSettings.current&&JSON.stringify(draftSettings.current)===JSON.stringify(lastEngineSettings.current))setSettings(data.session.settings);lastEngineSettings.current=data.session.settings}setOffline(false);setCpuHistory(h=>[...h.slice(-23),data.hardware.cpu_percent??0]);if(data.hardware.cpu_power?.watts!=null)setCpuPowerHistory(h=>[...h.slice(-23),data.hardware.cpu_power.watts]);if(data.hardware.gpu?.power_watts!=null)setPowerHistory(h=>[...h.slice(-23),data.hardware.gpu.power_watts/(data.hardware.gpu.power_limit_watts||575)*100]);}catch{setOffline(true)}finally{running=false}};
    poll();const interval=setInterval(poll,1500);return()=>clearInterval(interval)},[]);
  useEffect(()=>{if(logs===null)return;const interval=setInterval(()=>api('/api/logs').then(d=>setLogs(d.lines)).catch(()=>{}),1200);return()=>clearInterval(interval)},[logs!==null]);
  useEffect(()=>{if(view==='benchmarks')api('/api/benchmarks').then(setBenchmarks).catch(()=>{});},[view,session?.benchmark?.state]);
  useEffect(()=>{if(view==='profiles'){api('/api/profiles').then(setProfiles).catch(()=>{});api('/api/profiles?trash=true').then(setDeletedProfiles).catch(()=>{})}},[view]);
  useEffect(()=>{if(toast){const id=setTimeout(()=>{setToast('');setUndoProfile(null)},8000);return()=>clearTimeout(id)}},[toast]);
  const jumpToLatest=()=>{followTail.current=true;setShowLatest(false);if(chatRef.current)chatRef.current.scrollTop=chatRef.current.scrollHeight};
  useLayoutEffect(()=>{if(followTail.current&&chatRef.current)chatRef.current.scrollTop=messages.length?chatRef.current.scrollHeight:0},[messages,streaming,view,tab]);
  useEffect(()=>{const content=chatContentRef.current;if(!content)return;const observer=new ResizeObserver(()=>{if(followTail.current&&chatRef.current)chatRef.current.scrollTop=chatRef.current.scrollHeight});observer.observe(content);return()=>observer.disconnect()},[view,tab,selected?.id,messages.length===0]);
  useEffect(()=>{const el=textRef.current;if(el){el.style.height='auto';el.style.height=Math.min(el.scrollHeight,160)+'px'}},[input,view]);

  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(event.key==='Escape'){setLogs(null);setSaveOpen(false)}if(event.key==='/'&&!(event.target instanceof HTMLInputElement)&&!(event.target instanceof HTMLTextAreaElement)){event.preventDefault();document.querySelector<HTMLInputElement>('input[aria-label="Search models"]')?.focus()}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[]);

  const action=async(fn:()=>Promise<void>)=>{setActing(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setActing(false)}};
  const load=()=>action(async()=>{await api('/api/load',settings);setUsedContext(null);const data=await api('/api/status');setStatus(data)});
  const unload=()=>action(async()=>{await api('/api/unload',{});setStatus(await api('/api/status'))});
  const quit=()=>action(async()=>{await api('/api/quit',{});stopped.current=true;setClosed(true);setStatus(null);setOffline(false)});
  const stop=async()=>{controller.current?.abort();await api('/api/cancel',{}).catch(()=>{});setStreaming(false)};
  const addImage=(file:File|undefined)=>{
    if(!file)return;
    if(!settings?.vision){setError(selected?.vision?'Turn on the vision tower in Run settings, then reload to send images.':'This model is text-only. Select a model with vision to send an image.');return}
    if(streaming){setError('Wait for this reply or stop it before attaching an image.');return}
    if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('Choose a PNG, JPEG or WebP image.');return}
    if(file.size>12_000_000){setError('Please use an image smaller than 12 MB.');return}
    setError('');const reader=new FileReader();reader.onerror=()=>setError('This image could not be read. Try attaching it again.');
    reader.onload=()=>{setAttachment(String(reader.result));setTab('chat');textRef.current?.focus()};reader.readAsDataURL(file);
  };
  const pasteImage=(event:React.ClipboardEvent)=>{const item=Array.from(event.clipboardData.items).find(item=>item.kind==='file'&&item.type.startsWith('image/'));if(item){event.preventDefault();addImage(item.getAsFile()||undefined)}};
  const dropImage=(event:React.DragEvent)=>{event.preventDefault();setDragging(false);addImage(event.dataTransfer.files[0])};
  const copyReply=async(text:string,index:number)=>{try{await writeClipboard(text);setCopyIndex(index);setTimeout(()=>setCopyIndex(null),2000)}catch{setError('Clipboard access was unavailable. Select the text and use Ctrl+C.')}};
  const profileConfig=(profile:Profile)=>JSON.stringify({name:profile.name,settings:profile.settings},null,2);
  const copyProfileConfig=async(profile:Profile)=>{try{await writeClipboard(profileConfig(profile));setCopiedProfileId(profile.id);setTimeout(()=>setCopiedProfileId(id=>id===profile.id?null:id),2000)}catch{setError('Clipboard access was unavailable. Select the configuration and use Ctrl+C.')}};
  const send=async()=>{if(!input.trim()&&!attachment||!active||dirty||busy||!settings)return;setError('');const user:Message={role:'user',content:input.trim()||'Describe this image.',image:attachment};const history=[...messages.filter(m=>!m.error),user];setMessages([...history,{role:'assistant',content:''}]);setInput('');setAttachment(undefined);followTail.current=true;setShowLatest(false);setStreaming(true);controller.current=new AbortController();
    try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json','X-Lumen-Local':'1'},body:JSON.stringify({messages:history.map(m=>({role:m.role,content:m.image?[{type:'text',text:m.content},{type:'image_url',image_url:{url:m.image}}]:m.content,...(m.role==='assistant'&&m.reasoning?{reasoning_content:m.reasoning}:{})})),max_output:settings.max_output,temperature:settings.temperature,reasoning_effort:settings.reasoning_effort}),signal:controller.current.signal});
      if(!response.ok)throw new Error((await response.json()).detail);const reader=response.body!.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop()||'';for(const chunk of events){if(!chunk.startsWith('data: '))continue;const event=JSON.parse(chunk.slice(6));if(event.type==='error')throw new Error(event.message);if(event.type==='context')setUsedContext(event.input_tokens);if(event.type==='token')setMessages(ms=>ms.map((m,i)=>i===ms.length-1?{...m,content:m.content+event.text,reasoning:(m.reasoning||'')+event.reasoning}:m));if(event.type==='cancelled')setMessages(ms=>ms.map((m,i)=>i===ms.length-1?{...m,cancelled:true}:m));if(event.type==='complete'){setUsedContext(event.usage.total_tokens);setMessages(ms=>ms.map((m,i)=>i===ms.length-1?{...m,metrics:event}:m))}}}
    }catch(e){if((e as Error).name==='AbortError'){setMessages(ms=>ms.map((m,i)=>i===ms.length-1?{...m,cancelled:true}:m))}else{const message=(e as Error).message;setError(message);setMessages(ms=>ms.map((m,i)=>i===ms.length-1?{...m,content:m.content||message,error:true}:m))}}finally{setStreaming(false);controller.current=null}};
  const openSave=(mode:'create'|'update'|'rename'='create',target?:Profile)=>{setProfileError('');setSaveMode(mode);setSaveTarget(target||editingProfile||null);setProfileName(mode==='create'?`${selected?.title} · ${short(settings?.context||262144)} ${settings?.kv||'Q8'}`:(target||editingProfile)?.name||'');setSaveOpen(true)};
  const save=async()=>{if(acting)return;setActing(true);setProfileError('');try{
    const body={name:profileName.trim(),settings:saveMode==='rename'?saveTarget?.settings:settings};
    const saved:Profile[]=await api(saveMode==='create'?'/api/profiles':`/api/profiles/${saveTarget?.id}`,body,saveMode==='create'?'POST':'PUT');
    setProfiles(saved);if(saveMode!=='rename')setEditingId(saved.find(p=>p.name===body.name)?.id||null);setSaveOpen(false);setToast(saveMode==='create'?'Profile saved':saveMode==='rename'?'Profile renamed':'Profile updated');
  }catch(e){setProfileError((e as Error).message)}finally{setActing(false)}};
  const removeProfile=(profile:Profile)=>action(async()=>{setProfiles(await api(`/api/profiles/${profile.id}`,{},'DELETE'));setDeletedProfiles(await api('/api/profiles?trash=true'));if(editingId===profile.id)setEditingId(null);setUndoProfile(profile);setToast(`“${profile.name}” moved to Recently deleted`)});
  const restoreProfile=(profile:Profile)=>action(async()=>{setProfiles(await api(`/api/profiles/${profile.id}/restore`,{}));setDeletedProfiles(await api('/api/profiles?trash=true'));setUndoProfile(null);setToast('Profile restored')});
  const useProfile=(profile:Profile,loadNow=false)=>{const model=models.find(m=>m.id===profile.settings.model_id);if(!model){setError('This profile’s model is no longer in the library. Reconnect its drive and refresh the library.');return}choose(model,profile.settings,profile);if(loadNow)action(async()=>{await api('/api/load',profile.settings);setUsedContext(null);setStatus(await api('/api/status'))});else setToast('Edit the settings on the right, then choose Save changes.')};
  const runBenchmark=()=>action(async()=>{await api('/api/benchmark',{reasoning_effort:active?settings?.reasoning_effort:session?.settings?.reasoning_effort});setView('benchmarks');setStatus(await api('/api/status'))});

  const filtered=models.filter(m=>(showAll||m.recommended||!!query)&&(m.name+' '+m.format).toLowerCase().includes(query.toLowerCase()));
  const allCount=models.filter(m=>!m.recommended).length;
  return <div className="app-shell">
    <aside className="sidebar">
      <a className="brand" href="/" onClick={e=>{e.preventDefault();setView('workbench')}} aria-label="Lumen home"><span className="brand-mark"><Layers size={22}/></span><span>Lumen<small>LOCAL MODEL WORKBENCH</small></span></a>
      <nav aria-label="Main navigation">{[{id:'workbench',label:'Workbench',icon:MessageSquare},{id:'benchmarks',label:'Benchmarks',icon:Gauge},{id:'profiles',label:'Saved profiles',icon:Save}].map(({id,label,icon:Icon})=><button key={id} className={view===id?'nav-item current':'nav-item'} onClick={()=>setView(id as any)}><Icon size={17}/>{label}{id==='profiles'&&profiles.length>0&&<span className="nav-count">{profiles.length}</span>}</button>)}</nav>
      <div className="library-heading"><span>MODEL LIBRARY</span><button className="icon-btn" title="Refresh model library" onClick={()=>refresh()}><RefreshCw size={14}/></button></div>
      <label className="search"><Search size={15}/><input aria-label="Search models" placeholder="Find a model…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>/</kbd></label>
      <div className="library-list">{filtered.map(model=><button className={`model-item ${selected?.id===model.id?'selected':''}`} disabled={streaming} key={model.id} onClick={()=>choose(model)}><div className={`model-symbol ${model.name.startsWith('DeepSeek')?'blue':''}`}>{model.name.startsWith('DeepSeek')?'D':'Q'}</div><div className="model-copy"><strong>{model.title}</strong><span>{model.format} · {model.quant}</span><small>{model.vision?<><Eye size={11}/> Vision</>:<>Text only</>}<span className={model.issues.length?'issue-dot':'local-dot'}/>{model.issues.length?'Incomplete':'Local'}</small></div>{session?.model?.id===model.id&&ready&&<span className="running-dot" title="Loaded"/>}</button>)}{filtered.length===0&&<p className="empty-library">{models.length?'No matching models.':'Scanning your model library…'}</p>}
      {!query&&allCount>0&&<button className="more-models" onClick={()=>setShowAll(!showAll)}><ChevronDown size={14} className={showAll?'rotate':''}/>{showAll?'Show recommended models':`${allCount} more local variants`}</button>}</div>
      <div className="sidebar-bottom"><div><span className="local-indicator"/>On your computer</div><p>Your models. Your conversations.<br/>Inference stays on this machine.</p><div className="path" title={modelRoot}><HardDrive size={12}/>{modelRoot.split('/').slice(-2).join('/')||'AI/models'}</div><button className="quit-button" disabled={acting||busy||closed} onClick={quit}><Power size={13}/>Quit Lumen</button></div>
    </aside>

    <div className="main-shell">
      <header className="topbar"><div className="breadcrumbs">Workspace <span>/</span><strong>{view==='workbench'?'Model workbench':view==='benchmarks'?'Benchmarks':'Saved profiles'}</strong></div><div className="topbar-right"><span className={`status-pill ${offline?'bad':ready?'good':''}`}><i/>{closed?'Lumen closed':offline?'Connection lost':loading?'Loading engine':busy?'Processing request':ready?'Model ready':'No model loaded'}</span>{session?.busy&&!streaming&&<button className="secondary" onClick={stop}><Square size={12}/>Stop request</button>}<button className="icon-btn" title="View engine logs" onClick={()=>{setLogs([]);api('/api/logs').then(d=>setLogs(d.lines))}}><Terminal size={18}/></button></div></header>
      <section className="hardware-bar" aria-label="Live system metrics">
        <Metric icon={Zap} label="GPU POWER" value={number(gpu?.power_watts,0)} unit="W" detail={gpu?`${number(gpu.power_limit_watts,0)} W power limit · ${number(gpu.temperature_c,0)}°C`:'Waiting for GPU telemetry'} history={powerHistory}/>
        <Metric icon={Activity} label="CPU POWER" value={number(hardware?.cpu_power?.watts,1)} unit="W" detail={hardware?.cpu_power?.watts!=null?'CPU package · includes SoC':hardware?.cpu_power?.detail||'Reading package sensor…'} history={cpuPowerHistory}/>
        <Metric icon={Layers} label="VRAM" value={gib(gpu?.used_bytes)} unit={`/ ${gib(gpu?.total_bytes)} GiB`} detail={gpu?.name?.replace('NVIDIA GeForce ','')||'GPU unavailable'} percent={gpu?.total_bytes?gpu.used_bytes/gpu.total_bytes*100:null}/>
        <Metric icon={Database} label="SYSTEM RAM" value={gib(ram?.used_bytes)} unit={`/ ${gib(ram?.total_bytes)} GiB`} detail="Used / total · available memory excluded" percent={ram?.total_bytes?ram.used_bytes/ram.total_bytes*100:null}/>
        <Metric icon={Cpu} label="CPU USAGE" value={number(hardware?.cpu_percent,0)} unit="%" detail={`${hardware?.cpu_count||'—'} logical cores · system-wide`} history={cpuHistory}/>
      </section>
      <section className="performance-strip" aria-label="Response performance"><div className="performance-heading"><span className="eyebrow">LAST RESPONSE</span><span>{busy?(streaming&&!messages.at(-1)?.content?'Processing prompt…':'Request in progress…'):session?.last_usage?'Measured by the engine':'Send a message to measure'}</span></div><Performance metrics={session?.last_usage}/></section>
      {closed&&<div className="note"><Power size={18}/><p>Lumen is closed and the model is unloaded. Open Lumen from your application menu to return.</p></div>}
      {(error||session?.error||offline)&&<div role="alert" className="error-banner"><CircleHelp size={18}/><span>{error||session?.error||(offline?'The local server is unavailable. Reopen Lumen using its launcher.':'')}</span><button className="icon-btn" onClick={()=>{setError('');setLogs([]);api('/api/logs').then(d=>setLogs(d.lines))}}>View logs</button></div>}
      {inventoryErrors.length>0&&<details className="inventory-errors"><summary>{inventoryErrors.length} library inspection notice(s)</summary>{inventoryErrors.map(e=><p key={e}>{e}</p>)}</details>}

      {view==='workbench'&&selected&&settings?<div className="workbench">
        <main className={`conversation ${dragging?'dragging':''}`} onPaste={pasteImage} onDragOver={e=>{e.preventDefault();if(e.dataTransfer.types.includes('Files'))setDragging(true)}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDragging(false)}} onDrop={dropImage}>
          <div className="model-heading"><div><div className="eyebrow"><span className="tiny-line"/>{selected.recommended?'YOUR 3-BIT COLLECTION':'LOCAL CHECKPOINT'}</div><h1>{selected.title}</h1><div className="model-badges"><span>{selected.format}</span><span>{selected.quant}</span>{selected.vision&&<span><Eye size={12}/>Vision</span>}<span>{number(selected.bytes/1e9)} GB on disk</span></div></div><button className="secondary save-setup" onClick={()=>openSave(editingProfile?'update':'create')}><Save size={16}/>{editingProfile?'Save changes':'Save profile'}</button></div>
          {editingProfile&&<div className="editing-banner"><Save size={15}/><span><strong>{editingProfile.name}</strong><small>{profileDirty?'Unsaved changes':'Saved profile'} · Adjust settings on the right</small></span><button className="text-button" onClick={()=>openSave('create')}>Save as new</button></div>}
          <div className="workbench-tabs"><button className={tab==='chat'?'active':''} onClick={()=>setTab('chat')}><MessageSquare size={15}/>Conversation</button><button className={tab==='details'?'active':''} onClick={()=>setTab('details')}><Layers size={15}/>Model details</button><div className="tabs-spacer"/><button disabled={streaming||!messages.length} onClick={()=>{setMessages([]);setUsedContext(null);followTail.current=true;setShowLatest(false)}} title="Start a new conversation"><Plus size={15}/>New chat</button></div>
          {tab==='details'?<div className="details-panel"><h2>A closer look</h2><p>The files stay in your existing model library.</p><dl><dt>Architecture</dt><dd>{selected.architecture}</dd><dt>Native context limit</dt><dd>{number(selected.context,0)} tokens</dd><dt>Vision component</dt><dd>{selected.vision?'Identified in checkpoint':'Not identified / text-only model'}</dd><dt>Prediction component</dt><dd>{selected.mtp?'MTP weights identified':'Not identified'}</dd><dt>Download verification</dt><dd>{selected.receipt?.status==='verified'?`Verified ${new Date(selected.receipt.verified_utc).toLocaleString()}`:'No downloader receipt'}</dd><dt>Revision</dt><dd className="mono">{selected.receipt?.commit||'Local checkpoint'}</dd><dt>Location</dt><dd className="mono">{selected.path}</dd></dl>{selected.issues.map(issue=><p className="warning" key={issue}>{issue}</p>)}<div className="note"><CircleHelp size={18}/><p>A configured 256K capacity and a successful full-length request are separate tests. Benchmark results record the actual prompt length and settings.</p></div>{active&&<details><summary>Effective engine settings</summary><pre>{JSON.stringify(session.effective,null,2)}</pre></details>}</div>:
          <div className="chat-stage"><div className="chat-scroll" ref={chatRef} aria-label="Conversation messages" tabIndex={0} onScroll={e=>{const el=e.currentTarget;const near=el.scrollHeight-el.scrollTop-el.clientHeight<64;followTail.current=near;setShowLatest(!near)}} onWheel={e=>{if(e.deltaY<0)followTail.current=false}}>
          {messages.length===0?<div className="welcome"><div className="welcome-orbit"><div className="orbit-ring"/><Sparkles size={32}/><span className="orbit-point"/></div><div className="eyebrow">A LITTLE SPACE TO THINK BIG</div><h2>{active?'What shall we explore?':'Your next idea starts here.'}</h2><p>{active?'Your model is ready. Ask a question, share an image, or put it through its paces.':'Choose your settings, load the model, and make room for a longer conversation.'}</p><div className="prompt-cards"><button onClick={()=>setInput('Help me design a clear, maintainable Python application. Start by explaining your approach.')}><span className="prompt-icon"><Terminal size={17}/></span><strong>Build something</strong><span>Work through code and ideas</span><ArrowUpRight size={16}/></button><button onClick={()=>{if(settings.vision)fileRef.current?.click();else setInput('Explain how CPU and GPU memory work together when running a large language model.')}}><span className="prompt-icon peach"><Eye size={17}/></span><strong>{settings.vision?'Look a little closer':'Understand something'}</strong><span>{settings.vision?'Bring an image into the conversation':'Make a complex topic feel simple'}</span><ArrowUpRight size={16}/></button></div><div className="welcome-foot"><span className="local-indicator"/>Local inference · {short(settings.context)} context capacity · {settings.kv} cache</div></div>:
          <div className="messages" ref={chatContentRef}>{messages.map((message,i)=><article key={i} className={`message ${message.role} ${message.error?'failed':''}`}><div className="message-avatar">{message.role==='assistant'?<Sparkles size={16}/>: 'R'}</div><div className="message-body"><div className="message-author">{message.role==='user'?'You':'Lumen'}<span>{message.role==='assistant'?selected.title:''}</span>{message.content&&<button className="copy-message icon-btn" aria-label={message.role==='assistant'?'Copy answer':'Copy message'} onClick={()=>copyReply(message.content,i)}>{copyIndex===i?<Check size={14}/>:<Copy size={14}/>}</button>}</div>{message.image&&<img className="message-image" src={message.image} alt="Uploaded image"/>}{message.reasoning&&<details className="reasoning"><summary>Thinking</summary><Markdown text={message.reasoning}/></details>}<div className="markdown"><Markdown text={message.content}/></div>{streaming&&i===messages.length-1&&<span className="typing"><i/><i/><i/></span>}{message.cancelled&&<div className="response-metrics"><Square size={11}/>Stopped · partial answer</div>}{message.metrics?.finish_reason==='length'&&<p className="output-limit-note">Output limit reached. Increase Maximum output for more room to think and answer.</p>}{message.metrics&&<Performance metrics={message.metrics} compact/>}</div></article>)}<div ref={bottomRef}/></div>}
          </div>{showLatest&&<button className="jump-latest" onClick={jumpToLatest}><ArrowDown size={15}/>Jump to latest</button>}</div>}
          {dragging&&<div className="drop-hint"><ImagePlus size={22}/>Drop a screenshot or image here</div>}
          <div className="composer-wrap"><div className="message-options"><label><Sparkles size={14}/><span>Thinking</span><select aria-label="Reasoning level" value={settings.reasoning_effort} disabled={(selected.reasoning?.options.length||1)<2} onChange={e=>update('reasoning_effort',e.target.value)}>{(selected.reasoning?.options||['default']).map(value=><option key={value} value={value}>{effortLabel(value)}{value==='default'&&selected.reasoning?.default_effort?` · ${effortLabel(selected.reasoning.default_effort)}`:''}</option>)}</select></label><small>Next message · no reload</small></div>{attachment&&<div className="attachment"><img src={attachment} alt="Image to send"/><span>Image attached</span><button className="icon-btn" onClick={()=>setAttachment(undefined)} aria-label="Remove attached image"><X size={15}/></button></div>}<div className={`composer ${!active?'inactive':''}`}><textarea ref={textRef} aria-label="Message" placeholder={active?(settings.vision?'Ask anything. Paste a screenshot with Ctrl+V…':'Ask anything…'):'Write a message. Load the model when you’re ready.'} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}} rows={2}/><div className="composer-toolbar"><button className="icon-btn" disabled={!settings.vision||streaming} aria-label="Attach image" title={settings.vision?'Attach an image, or paste a screenshot with Ctrl+V':'This profile has vision disabled'} onClick={()=>fileRef.current?.click()}><ImagePlus size={19}/></button><span>{settings.vision?'Paste, drop or attach an image':'Text only'}</span><div className="toolbar-spacer"/><small>Shift + Enter for a new line</small>{streaming?<button className="send-button" onClick={stop} aria-label="Stop generation"><Square size={16}/></button>:<button className="send-button" disabled={!active||dirty||busy||(!input.trim()&&!attachment)} onClick={send} aria-label="Send message"><ArrowUpRight size={20}/></button>}</div></div><div className="context-footer"><span>{usedContext==null?'Context is ready for a fresh conversation':`${number(usedContext,0)} / ${number(settings.context,0)} tokens used`}</span><span>{active?(dirty?'Reload to apply settings':'Connected locally'):'Model not loaded'}</span></div></div>
        </main>

        <aside className="settings-panel"><div className="settings-title"><Settings2 size={17}/><h2>Run settings</h2><span className="small-badge">LOCAL</span></div><p className="settings-intro">Make this model work for you.</p><div className="settings-fields"><label className="field">Inference engine<select value={settings.engine} disabled={busy||loading} onChange={e=>update('engine',e.target.value)}><option value="auto">Auto · {selected.engines[0]==='exl3'?'ExLlamaV3':selected.engines[0]}</option>{status?.engines?.map((engine:any)=><option key={engine.id} value={engine.id} disabled={!selected.engines.includes(engine.id)||!engine.installed}>{engine.name}{!engine.installed?' · not installed':''}</option>)}</select><small>{selected.format==='EXL3'?'ExLlamaV3 + TabbyAPI · isolated CUDA runtime':installed?'Compatibility still needs qualification':'Install this engine to use this checkpoint'}</small></label>
          <label className="field">Context window<select value={settings.context} disabled={busy||loading} onChange={e=>update('context',Number(e.target.value))}>{[4096,8192,16384,32768,65536,131072,262144,524288,1048576].filter(v=>v<=selected.context).map(v=><option value={v} key={v}>{short(v)} tokens{v===262144?' · preferred':''}</option>)}</select><small>{number(settings.context,0)} tokens, including the answer</small></label>
          <div className="field"><span>KV cache precision</span><div className="segmented">{['FP16','Q8','Q4'].map(v=><button disabled={busy||loading} key={v} className={settings.kv===v?'chosen':''} onClick={()=>update('kv',v)}>{v}{v==='Q8'&&<span className="choice-dot"/>}</button>)}</div><small>{settings.kv==='Q8'?(selected.engines[0]==='vllm'?'FP8 cache · engine support required':'8-bit cache · preferred quality') :settings.kv==='Q4'?'4-bit cache · experimental quality trade-off':'16-bit cache · higher memory use'}</small></div>
          <div className="setting-switch"><div><label>Vision tower</label><small>{selected.vision?'Understand uploaded images':'Text-only checkpoint'}</small></div><Toggle label="Vision tower" checked={settings.vision} disabled={!selected.vision||busy||loading} onChange={v=>update('vision',v)}/></div>
          <div className="setting-switch"><div><label>Prediction acceleration</label><small>{selected.mtp?'MTP · test its speed benefit':'No MTP component identified'}</small></div><Toggle label="Prediction acceleration" checked={settings.prediction==='mtp'} disabled={!selected.mtp||selected.engines[0]!=='exl3'||busy||loading} onChange={v=>update('prediction',v?'mtp':'off')}/></div>
          {settings.prediction==='mtp'&&<label className="field compact">Draft tokens<select value={settings.draft_tokens} disabled={busy||loading} onChange={e=>update('draft_tokens',Number(e.target.value))}>{Array.from({length:selected.draft_limit||4},(_,i)=>i+1).map(n=><option key={n}>{n}</option>)}</select></label>}
          <label className="field">Maximum output<select value={settings.max_output} onChange={e=>update('max_output',Number(e.target.value))}>{[256,512,1024,2048,4096,8192,16384,32768].filter(n=>n<settings.context).map(n=><option value={n} key={n}>{short(n)} tokens</option>)}</select><small>Thinking and answer share this limit. No separate thinking cap.</small></label>
          <details className="advanced"><summary><Settings2 size={14}/>Fine-tune<ChevronDown size={14}/></summary><div><label className="field">{selected.engines[0]==='gguf'?'CPU layer share':selected.engines[0]==='vllm'?'CPU weight offload':'CPU expert share'}<span className="range-value">{settings.cpu_percent}%</span><input type="range" aria-label="CPU memory share" min="0" max="100" step="5" value={settings.cpu_percent} disabled={busy||loading} onChange={e=>update('cpu_percent',Number(e.target.value))}/><small>{selected.engines[0]==='exl3'?'Experts run in RAM; Qwen’s n-gram table stays in RAM.':'Higher values move more work or weights to system RAM.'}</small></label><label className="field">CPU threads<input type="number" min="1" max="64" value={settings.cpu_threads} onChange={e=>update('cpu_threads',Number(e.target.value))}/></label><label className="field">Prompt chunk size<select value={settings.chunk_size} onChange={e=>update('chunk_size',Number(e.target.value))}>{[256,512,1024,2048,4096].map(n=><option key={n}>{n}</option>)}</select></label><label className="field">Temperature <span className="range-value">{settings.temperature.toFixed(1)}</span><input type="range" min="0" max="2" step="0.1" value={settings.temperature} onChange={e=>update('temperature',Number(e.target.value))}/></label></div></details>
        </div><div className="load-area">{loading?<><div className="load-progress"><LoaderCircle size={16} className="spin"/><span>Loading · {number(session.elapsed_seconds,0)}s</span></div><p className="load-log" title={session.latest_log}>{session.latest_log||'Preparing engine…'}</p><button className="secondary full" onClick={unload} disabled={acting}>Cancel load</button></>:<><button className="primary full" onClick={load} disabled={acting||busy||!installed||!!selected.issues.length}>{acting?<LoaderCircle className="spin" size={17}/>:<Play size={16}/>} {active?(dirty?'Apply and reload':'Reload model'):'Load model'}</button>{active&&<button className="unload-button" onClick={unload} disabled={acting||busy}><Square size={11}/>Unload model</button>}</>}
        {!installed&&!closed&&status&&<p className="warning">This engine is not installed yet.</p>}<div className="settings-note"><CircleHelp size={13}/><span>{dirty?'Settings changed. Choose Apply and reload to use them.':'Thinking, output length and temperature apply to the next message. Other settings need a reload.'}</span></div></div></aside>
      </div>:view==='benchmarks'?<main className="page"><div className="page-heading"><div><div className="eyebrow">MEASURED ON YOUR MACHINE</div><h1>Put performance in perspective.</h1><p>Prompt processing, decoding, and the settings behind every run.</p></div><button className="primary" disabled={!ready||busy||acting} onClick={runBenchmark}><Gauge size={17}/>Run 3-prompt benchmark</button></div>{session?.benchmark?.state==='running'&&<div className="note"><LoaderCircle className="spin" size={18}/><p>Benchmark running · {session.benchmark.completed} of 3 prompts complete. Hardware metrics remain live above.</p><button className="secondary" onClick={stop}>Stop</button></div>}<div className="benchmark-explainer"><div><span>50</span><small>tok/s · Qwen target</small></div><div><span>20</span><small>tok/s · DeepSeek target</small></div><p>Targets apply to short prompts with the full context capacity configured. Filled-context and vision correctness need their own tests.</p></div>{benchmarks.length===0?<div className="empty-page"><Gauge size={38}/><h2>Your first measurement belongs here.</h2><p>Load a model and run the benchmark. Results are saved locally.</p></div>:benchmarks.map(result=><article className="benchmark-card" key={result.id}><div><span className="small-badge">{result.engine} · {result.state}</span><h2>{result.model.title}</h2><p>{new Date(result.created*1000).toLocaleString()} · {short(result.settings.context)} capacity · {result.settings.kv} cache · Vision {result.settings.vision?'on':'off'} · {result.settings.cpu_percent}% CPU · MTP {result.settings.prediction==='mtp'?`${result.settings.draft_tokens} tokens`:'off'}</p></div><div className="benchmark-speeds"><div className="benchmark-number prompt-number">{number(medianPrompt(result))}<span>prompt tok/s · median</span></div><div className="benchmark-number">{number(result.median_tps)}<span>decode tok/s · median</span></div></div>{result.error&&<p className="warning">{result.error}</p>}<details><summary>Individual runs & settings</summary><pre>{JSON.stringify({settings:result.settings,runs:result.runs},null,2)}</pre></details><button className="secondary" onClick={()=>{const model=models.find(m=>m.id===result.model.id);if(model){choose(model,result.settings);setToast('Benchmark settings applied. Load to use them.')}}}>Use these settings</button></article>)}</main>:view==='profiles'?<main className="page profiles-page"><div className="page-heading"><div><div className="eyebrow">YOUR EVERYDAY SETUPS</div><h1>Saved profiles</h1><p>One click to load. Easy to adjust, rename, or keep as a new setup.</p></div><button className="primary" disabled={!settings} onClick={()=>openSave('create')}><Plus size={17}/>Save current setup</button></div>
        <div className="profile-toolbar"><button className={!showDeleted?'chosen':''} onClick={()=>setShowDeleted(false)}>Saved <span>{profiles.length}</span></button><button className={showDeleted?'chosen':''} onClick={()=>setShowDeleted(true)}><Trash2 size={14}/>Recently deleted <span>{deletedProfiles.length}</span></button></div>
        {(showDeleted?deletedProfiles:profiles).length===0?<div className="empty-page"><Save size={38}/><h2>{showDeleted?'Nothing in Recently deleted.':'Keep a setup you like.'}</h2><p>{showDeleted?'Deleted profiles can be restored here.':'Select a model, adjust its settings, then choose Save profile.'}</p>{!showDeleted&&<button className="secondary" onClick={()=>setView('workbench')}>Open workbench</button>}</div>:<div className="profile-grid">{(showDeleted?deletedProfiles:profiles).map(profile=>{const model=models.find(m=>m.id===profile.settings.model_id);return <article className={`profile-card ${editingId===profile.id?'profile-selected':''}`} key={profile.id}><div className="profile-card-top"><span className="prompt-icon"><Save size={18}/></span>{!showDeleted&&<div><button className="icon-btn" aria-label={`Rename ${profile.name}`} title="Rename profile" onClick={()=>openSave('rename',profile)}><Pencil size={15}/></button><button className="icon-btn delete-profile" disabled={acting} aria-label={`Delete ${profile.name}`} title="Move to Recently deleted" onClick={()=>removeProfile(profile)}><Trash2 size={15}/></button></div>}</div><h2>{profile.name}</h2><p className="profile-model">{model?.title||'Model unavailable'}</p><div className="profile-specs"><span>{short(profile.settings.context)} context</span><span>{profile.settings.kv} cache</span><span>{profile.settings.cpu_percent}% CPU</span><span>{profile.settings.vision?'Vision on':'Text only'}</span><span>MTP {profile.settings.prediction==='mtp'?profile.settings.draft_tokens:'off'}</span><span>Thinking: {effortLabel(profile.settings.reasoning_effort)}</span></div><div className="profile-config"><div className="profile-config-heading"><span>Full configuration</span><button type="button" className="copy-profile-config" aria-label={`Copy full configuration for ${profile.name}`} onClick={()=>copyProfileConfig(profile)}>{copiedProfileId===profile.id?<Check size={13}/>:<Copy size={13}/>} {copiedProfileId===profile.id?'Copied':'Copy config'}</button></div><pre tabIndex={0}>{profileConfig(profile)}</pre></div><div className="profile-actions">{showDeleted?<button className="secondary" disabled={acting} onClick={()=>restoreProfile(profile)}><RotateCcw size={15}/>Restore profile</button>:<><button className="primary" disabled={busy||loading||acting||!model} onClick={()=>useProfile(profile,true)}><Play size={14}/>Load profile</button><button className="secondary" disabled={busy||loading||!model} onClick={()=>useProfile(profile)}><Settings2 size={14}/>Edit settings</button></>}</div></article>})}</div>}</main>:<main className="page empty-page"><LoaderCircle size={30} className="spin"/><h2>Opening your local library…</h2></main>}
      <footer className="statusbar"><span><span className={ready?'local-indicator':'idle-indicator'}/>{session?.engine==='exl3'?'ExLlamaV3 1.5.0':session?.engine||'Ready when you are'}</span><span>{session?.model?.title||'Your models stay on this computer'}</span><button onClick={()=>{setLogs([]);api('/api/logs').then(d=>setLogs(d.lines))}}><Terminal size={12}/>Engine log</button></footer>
    </div>
    <input ref={fileRef} type="file" hidden accept="image/png,image/jpeg,image/webp" onChange={e=>{addImage(e.target.files?.[0]);e.target.value=''}}/>
    {toast&&<div className="toast" role="status"><Check size={17}/><span>{toast}</span>{undoProfile&&<button onClick={()=>restoreProfile(undoProfile)}>Undo</button>}</div>}
    {logs!==null&&<Modal title="Engine log" onClose={()=>setLogs(null)} className="logs-dialog"><p className="dialog-description">Live output from the local inference engine.</p><pre className="engine-log">{logs.length?logs.join('\n'):'No engine output yet. Load a model to begin.'}</pre></Modal>}
    {saveOpen&&<Modal title={saveMode==='create'?'Save profile':saveMode==='rename'?'Rename profile':'Save changes'} onClose={()=>{if(!acting)setSaveOpen(false)}} className="profile-dialog"><p className="dialog-description">{saveMode==='rename'?'Give this setup a name that is easy to recognise.':saveMode==='update'?'Update this saved profile with the settings in your workbench.':'Keep this model and its settings together for next time.'}</p><form onSubmit={e=>{e.preventDefault();save()}}><label className="field">Profile name<input autoFocus required value={profileName} maxLength={80} placeholder="e.g. DeepSeek · everyday chat" onChange={e=>setProfileName(e.target.value)}/></label>{saveMode!=='rename'&&settings&&<div className="save-summary"><strong>{selected?.title}</strong><span>{short(settings.context)} context · {settings.kv} cache · {settings.cpu_percent}% CPU</span><span>{settings.vision?'Vision on':'Text only'} · MTP {settings.prediction==='mtp'?settings.draft_tokens:'off'}</span></div>}{profileError&&<div role="alert" className="dialog-error">{profileError}</div>}<div className="dialog-actions"><button type="button" className="secondary" disabled={acting} onClick={()=>setSaveOpen(false)}>Cancel</button><button type="submit" className="primary" disabled={!profileName.trim()||acting}>{acting?<LoaderCircle size={16} className="spin"/>:<Save size={16}/>} {saveMode==='create'?'Save profile':saveMode==='rename'?'Rename profile':'Save changes'}</button></div></form></Modal>}

  </div>;
}

createRoot(document.getElementById('root')!).render(<App/>);
